general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.
  # Example: The below command launches Zebar.
  startup_commands: ['shell-exec zebar']

  # Commands to run just before the WM is shutdown.
  # Example: The below command kills Zebar.
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: 'monitor_focus'

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent windows.
  inner_gap: '3px'

  # Gap between windows and the screen edge.
  outer_gap:
    top: '27px'
    right: '5px'
    bottom: '5px'
    left: '3px'

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: '#3ef904'

    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    # Change the corner style of the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    corner_style:
      enabled: false
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: 'square'

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: '#a1a1a1'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: 'square'

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: 'tiling'

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: 'F'
  - name: 'E'
  - name: 'W'
  - name: 'P'
  - name: 'M'
  - name: 'D'
  - name: '0'
  - name: 'O'
  - name: '9'
  - name: 'Terminal'

window_rules:
  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -2%']
        bindings: ['h', 'left']
      - commands: ['resize --width +2%']
        bindings: ['l', 'right']
      - commands: ['resize --height +2%']
        bindings: ['k', 'up']
      - commands: ['resize --height -2%']
        bindings: ['j', 'down']
      # Press enter/escape to return to default keybindings.
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter']

  # When enabled, all keybindings are disabled except for alt+shift+p which
  # returns to default keybindings.
  #- name: 'pause'
  #  keybindings:
  #    - commands: ['wm-disable-binding-mode --name pause']
  #      bindings: ['alt+shift+p']

keybindings:
  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['alt+h']
  - commands: ['focus --direction right']
    bindings: ['alt+l']
  - commands: ['focus --direction up']
    bindings: ['alt+k']
  - commands: ['focus --direction down']
    bindings: ['alt+j']

  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['alt+shift+h', 'alt+shift+left']
  - commands: ['move --direction right']
    bindings: ['alt+shift+l', 'alt+shift+right']
  - commands: ['move --direction up']
    bindings: ['alt+shift+k', 'alt+shift+up']
  - commands: ['move --direction down']
    bindings: ['alt+shift+j', 'alt+shift+down']

  # Resize focused window by a percentage or pixel amount.
  #- commands: ['resize --width -2%']
  #  bindings: ['alt+u']
  #- commands: ['resize --width +2%']
  #  bindings: ['alt+p']
  #- commands: ['resize --height +2%']
  #  bindings: ['alt+o']
  #- commands: ['resize --height -2%']
  #  bindings: ['alt+i']

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ['wm-enable-binding-mode --name resize']
    bindings: ['alt+r']

  # Disables all keybindings until alt+shift+p is pressed again.
  - commands: ['wm-enable-binding-mode --name pause']
    bindings: ['alt+shift+p']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['alt+v']

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ['wm-cycle-focus']
    bindings: ['alt+space']

  # Change the focused window to be floating.
  - commands: ['toggle-floating --centered']
    bindings: ['alt+shift+space']

  # Change the focused window to be tiling.
  - commands: ['toggle-tiling']
    bindings: ['alt+t']

  # Change the focused window to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['alt+z']

  # Minimize focused window.
  - commands: ['toggle-minimized']
    bindings: ['alt+j']

  # Close focused window.
  - commands: ['close']
    bindings: ['alt+shift+q']

  # Kill GlazeWM process safely.
  - commands: ['wm-exit']
    bindings: ['alt+shift+q+e']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['alt+shift+r']

  # Redraw all windows.
  - commands: ['wm-redraw']
    bindings: ['alt+shift+t']

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  #- commands: ['shell-exec powershell']
  #  bindings: ['alt+shift+enter']

  # Focus the next/previous workspace defined in `workspaces` config.
  - commands: ['focus --next-workspace']
    bindings: ['alt+]']
  - commands: ['focus --prev-workspace']
    bindings: ['alt+[']

  # Focus the workspace that last had focus.
  - commands: ['focus --recent-workspace']
    bindings: ['alt+<']

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace F'] # Web Browsers
    bindings: ['alt+f']
  - commands: ['focus --workspace E'] # Teams & Outlook
    bindings: ['alt+e']
  - commands: ['focus --workspace W'] # Connectwise
    bindings: ['alt+w']
  - commands: ['focus --workspace P'] # Password Managers
    bindings: ['alt+p']
  - commands: ['focus --workspace M'] # Virtual Machines
    bindings: ['alt+m']
  - commands: ['focus --workspace D'] # Empty Workspace
    bindings: ['alt+d']
  - commands: ['focus --workspace 0'] # Personal
    bindings: ['alt+0']
  - commands: ['focus --workspace O'] # For KeePass (Cuz it sucks)
    bindings: ['alt+o']
  - commands: ['focus --workspace 9'] # Empty Workspace 2
    bindings: ['alt+9']
  - commands: ['focus --workspace Terminal'] # Empty Workspace 2
    bindings: ['alt+enter']

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ['move-workspace --direction left']
    bindings: ['ctrl+alt+shift+h']
  - commands: ['move-workspace --direction right']
    bindings: ['ctrl+alt+shift+l']
  #- commands: ['move-workspace --direction up']
  #  bindings: ['alt+shift+d']
  #- commands: ['move-workspace --direction down']
  #  bindings: ['alt+shift+s']

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ['move --workspace F', 'focus --workspace F']
    bindings: ['alt+shift+f']
  - commands: ['move --workspace E', 'focus --workspace E']
    bindings: ['alt+shift+e']
  - commands: ['move --workspace W', 'focus --workspace W']
    bindings: ['alt+shift+w']
  - commands: ['move --workspace P', 'focus --workspace P']
    bindings: ['alt+shift+p']
  - commands: ['move --workspace M', 'focus --workspace M']
    bindings: ['alt+shift+m']
  - commands: ['move --workspace D', 'focus --workspace D']
    bindings: ['alt+shift+d']
  - commands: ['move --workspace 0', 'focus --workspace 0'] 
    bindings: ['alt+shift+0']
  - commands: ['move --workspace O', 'focus --workspace O']
    bindings: ['alt+shift+o']
  - commands: ['move --workspace 9', 'focus --workspace 9']
    bindings: ['alt+shift+9']
  - commands: ['move --workspace Terminal', 'focus --workspace 9']
    bindings: ['alt+shift+enter']
